/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassViewPanel.java
 *
 * Created on Jun 3, 2014, 9:38:07 PM
 */
package smartClassEx;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import smartDB.DBWrapper;

/**
 *
 * @author JITHIN.P
 */
public class ClassViewPanel extends javax.swing.JPanel
{

    /** Creates new form ClassViewPanel */
   
    public ClassViewPanel(SmartClassMain parent)
    {
        initComponents();
        setDialog() ;
    }
   
    private DefaultTableModel dtm ;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hideButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        hideButton.setText("Hide");
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Department");

        jLabel2.setText("Semester");

        jLabel3.setText("Class");

        jLabel4.setText("Start date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 217, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(hideButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hideButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        classTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        classTable.setFont(new java.awt.Font("Times New Roman", 1, 14));
        classTable.setModel( dtm = new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Class ID", "Department", "Semester", "Class", "Adviser", "Start date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        classTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(classTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_hideButtonActionPerformed

    void setUI()
    { 
        JMenuItem menuItemView= new JMenuItem("New exam");
        JMenuItem menuItemUpdate = new JMenuItem("Update");
        JMenuItem menuItemAddStudent = new JMenuItem("Add Student");
        JMenuItem menuItemReport= new JMenuItem("Report");
        JMenuItem menuItemWorking= new JMenuItem("Create new working day");
        
        menuItemReport.addActionListener(new ActionListener()
         {
            @Override
            public void actionPerformed(ActionEvent event)
            {
             
                 onReportActionPerformed(event);
            }

   
         });
        
        menuItemWorking.addActionListener(new ActionListener()
         {
            @Override
            public void actionPerformed(ActionEvent event)
            {
                 onWorkingDayActionPerformed(event);
            }

          

   
         });
        
        menuItemView.addActionListener(new ActionListener()
         {
            @Override
            public void actionPerformed(ActionEvent event)
            {
                 onNewExamActionPerformed(event);
            }

           
         });
        
        menuItemAddStudent.addActionListener(new ActionListener()
         {
            @Override
            public void actionPerformed(ActionEvent event)
            {
               onAddStudentActionPerformed(event);
              }
         });
        
         menuItemUpdate.addActionListener(new ActionListener()
         {
            @Override
            public void actionPerformed(ActionEvent event)
            {
               onAddStudentActionPerformed(event);
              }
         });
        
        popupMenu.add(menuItemView);
        popupMenu.add(menuItemUpdate);
        popupMenu.add(menuItemAddStudent);
        popupMenu.add(menuItemWorking);
        popupMenu.add(menuItemReport);
        classTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        classTable.setComponentPopupMenu(popupMenu);
        
    }
    
    
    private void setDialog() 
    {
        setUI();
        loadClassDetails();
      
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable classTable;
    private javax.swing.JButton hideButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    JPopupMenu popupMenu = new JPopupMenu();
   
 
    
     private void loadClassDetails()
    {
        String sQuery = "SELECT *FROM classdetails";
        try 
        {
            ResultSet resultSet = DBWrapper.getStatement().executeQuery(sQuery);
            while(resultSet.next())
            {
                String sClassID	= resultSet.getString(1);
                String sDepartment = resultSet.getString(2);
                String sSemester = resultSet.getString(3);
                String sClass = resultSet.getString(4);
                String sAdviser	= resultSet.getString(5);
                String sStartDate = resultSet.getString(6);
              
                Object object[] = new Object[] {sClassID, sDepartment, sSemester,sClass, sAdviser, sStartDate };
                dtm.addRow(object);
            
                System.out.println(sClassID);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(ClassViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

              private void onNewExamActionPerformed(ActionEvent event) 
                 {
                int nRow =  classTable.getSelectedRow();
                  String sClassId = (String) classTable.getValueAt(nRow, 0);
                    ExamDialog examDialog = new ExamDialog(null, true,sClassId);
                    examDialog.showDialog();
            }


    public void onAddStudentActionPerformed(ActionEvent event)
    {
      int nRow =  classTable.getSelectedRow();
      String sClassId = (String) classTable.getValueAt(nRow, 0);
      CreateStudentDialog createStudentDialog = new CreateStudentDialog(null, true,sClassId);
      createStudentDialog.showDialog();
    }
    
    public void onDataUpdated( String sClassId ) 
    {
        try {
            String sQuery = "SELECT *FROM classdetails where ClassID ='" +sClassId+ "'";
             ResultSet resultSet = DBWrapper.getStatement().executeQuery(sQuery);
              if(resultSet.next())
                {
                    String sClassID	= resultSet.getString(1);
                    String sDepartment = resultSet.getString(2);
                    String sSemester = resultSet.getString(3);
                    String sClass = resultSet.getString(4);
                    String sAdviser	= resultSet.getString(5);
                    String sStartDate = resultSet.getString(6);
                    Object object[] = new Object[] {sClassID, sDepartment, sSemester,sClass, sAdviser, sStartDate };
                    dtm.addRow(object);
                
                    System.out.println(sClassID);
                }
        } catch (SQLException ex) {
            Logger.getLogger(ClassViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }      
    
    public void onReportActionPerformed(ActionEvent event)
    {
      
    }
    
    public String getSelectedClassID()

    {
        int nRow =  classTable.getSelectedRow();
        String sClassId = (String) classTable.getValueAt(nRow, 0);
        return sClassId;   
    }
    
     private void onWorkingDayActionPerformed(ActionEvent event) 
     
     {
             
     }
    
    
}
