/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateClassDialog.java
 *
 * Created on Jun 2, 2014, 7:35:32 PM
 */
package smartClassEx;

import smartDB.Common;
import smartDB.DBWrapper;

/**
 *
 * @author JITHIN.P
 */
public class CreateClassDialog extends javax.swing.JDialog 
{

    /** Creates new form CreateClassDialog */
    private ClassViewPanel cViewPanel ;
    public CreateClassDialog(java.awt.Frame parent, boolean modal,ClassViewPanel cvPanel) 
    {
        super(parent, modal);
        initComponents();
        cViewPanel = cvPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departmentComboBox = new javax.swing.JComboBox();
        dateTextField = new javax.swing.JTextField();
        semesterComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        classIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stafTextField = new javax.swing.JTextField();
        oKButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Class"));

        jLabel1.setText("Start date");

        jLabel2.setText("Semester");

        jLabel3.setText("Department");

        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Department of Computer Science", "Department of Computer Application", "Department of Electonics Engineering", "Department of Electrical Engineering", "Department of Mechanical Engineering", "Department of Civil Engineering", "Department of Automobile Engineering", "Department of Applied Electronics", " " }));
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClassActionPerformed(evt);
            }
        });

        dateTextField.setText("yyyy-mm-dd");
        dateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onClassKeyTyped(evt);
            }
        });

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10", " " }));
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClassActionPerformed(evt);
            }
        });

        jLabel4.setText("Class");

        classComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        classComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClassActionPerformed(evt);
            }
        });

        jLabel5.setText("Class ID");

        classIDTextField.setEditable(false);

        jLabel6.setText("Staff Adviser");

        stafTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onClassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(classComboBox, 0, 91, Short.MAX_VALUE))
                    .addComponent(departmentComboBox, 0, 248, Short.MAX_VALUE)
                    .addComponent(stafTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(classIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(stafTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(classIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        oKButton.setText("OK");
        oKButton.setEnabled(false);
        oKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oKButton)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onClassKeyTyped
        // TODO add your handling code here:
      genarateID();
    }//GEN-LAST:event_onClassKeyTyped


    private void onClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClassActionPerformed
        // TODO add your handling code here:
        genarateID();
    }//GEN-LAST:event_onClassActionPerformed

    private void oKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oKButtonActionPerformed
        
        
       if( DBWrapper.insertData("INSERT INTO ClassDetails (ClassID, Department, Semester, Class, Adviser, StartDate,IsClosed)"
               + " VALUES ('"+genarateID()+"', '"+getDepartmentCode()+"', '"+getSemesterCode()
               +"', '"+getClassCode()+"', '"+getAdviserName()+"', '" +getStartDate() + "', 0 )"))
       {
           MessageBox.showMessage(this, "Class Inserted successfully...", "SmartClassEx",MessageType.SIMPLE);
           if(null != cViewPanel)
           {
               cViewPanel.onDataUpdated(genarateID());
           }
       }
       else
       {
           MessageBox.showMessage(this, "Class Insertion faild successfully...", "SmartClassEx",MessageType.SIMPLE);
       }
           
               
    }//GEN-LAST:event_oKButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CreateClassDialog dialog = new CreateClassDialog(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                DBWrapper.initDBWrapper();
                dialog.setVisible(true);
            }
        });
    }
  
    private String getStartDate()
    {
        return dateTextField.getText();
    }
     private String getSemesterCode()
    {
        String sSemester = String.valueOf(semesterComboBox.getSelectedItem()) ; 
        return sSemester;
    }
      private String getClassCode()
    {
        String sClass= String.valueOf(classComboBox.getSelectedItem()) ; 
   
        return sClass;
    }
    
      private String getAdviserName()
      {
          return stafTextField.getText();
      }
      
    private String getDepartmentCode()
    {
        String sDepartmentCode="CSE";
       /* String sDepartment = String.valueOf(semesterComboBox.getSelectedItem()) ; 
        for(int nI = 7; nI<sDepartment.length();nI++)
        {
         //(sDepartment.charAt(nI))
         {
             sDepartmentCode += sDepartment.charAt(nI);
         }
        }*/
        return sDepartmentCode;
    }
    private String getDateCode()
    {
        String sDate = dateTextField.getText();
        String sDateCode = "";
         for(int nI = 0; nI<sDate.length();nI++)
        {
         if('-' != sDate.charAt(nI))
         {
             sDateCode += sDate.charAt(nI);
         }
        }
        return sDateCode;
    }
    private String genarateID()
    {
        String sClass =getDepartmentCode()+getSemesterCode()+getClassCode()+getDateCode();
        classIDTextField.setText(sClass);
        oKButton.setEnabled(! stafTextField.getText().equals(""));
        return sClass;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox classComboBox;
    private javax.swing.JTextField classIDTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton oKButton;
    private javax.swing.JComboBox semesterComboBox;
    private javax.swing.JTextField stafTextField;
    // End of variables declaration//GEN-END:variables

    void showDialog()
    {
        Common.setPosition(this);
        setVisible(true);
    }
}
