/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SmartPanel.java
 *
 * Created on May 30, 2014, 8:13:27 AM
 */
package smartClassEx;

import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author JITHIN.P
 */
public  class SmartPanel extends javax.swing.JPanel {

    private boolean bShow;
    public Rectangle showRectangle;
    public Rectangle hideRectangle;
    /** Creates new form SmartPanel */
    public SmartPanel() {
        
        initComponents();
        initDialog();
        
    }
    public void setShow(boolean bValue)
    {
          bShow =bValue;
    }
    
    public void addComponent()
    {
        
    }
    
    public boolean gethow()
    {
        return bShow;
    }

    void setCommandNew(String sCommand) 
    {
       newButton.setText(sCommand);
    }
     void setCommandUpdate(String sCommand) 
    {
       updateButton.setText(sCommand);
    } 
     void setCommandView(String sCommand) 
    {
       viewButton.setText(sCommand);
    }
            
            
            
    private void initDialog()
    {
        bShow =true;
        showRectangle = this.getBounds();
        hideRectangle = new Rectangle(showRectangle.x, showRectangle.y, titlePanel.getBounds().width, titlePanel.getBounds().height+10);
        showHide();   
    }
    
    private void showHide()
    { 
        componentPanel.setVisible(bShow);
        if(bShow)
        {
           
            this.setBounds(showRectangle);
        }
        else
        {
           this.setBounds(hideRectangle); 
        }
        bShow = !bShow;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new CustomTitlePanel(Color.GRAY,Color.WHITE);
        titleLabel = new SmartLabel("View",Color.GRAY, Color.PINK);
        showHideButton = new SmartButton("^",Color.GRAY, Color.PINK);
        componentPanel = new javax.swing.JPanel();
        newButton = new SmartButton("New",Color.ORANGE, Color.BLUE);
        updateButton = new SmartButton("Update",Color.ORANGE, Color.BLUE);
        viewButton = new SmartButton("View",Color.ORANGE, Color.BLUE);

        titlePanel.setBackground(new java.awt.Color(227, 227, 227));
        titlePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Smart Panel");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        showHideButton.setText("^");
        showHideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addComponent(showHideButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSmartPanelActionPerformed(evt);
            }
        });

        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSmartPanelActionPerformed(evt);
            }
        });

        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSmartPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout componentPanelLayout = new javax.swing.GroupLayout(componentPanel);
        componentPanel.setLayout(componentPanelLayout);
        componentPanelLayout.setHorizontalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        componentPanelLayout.setVerticalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(componentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
       
        showHide();
        
        
    }//GEN-LAST:event_showHideButtonActionPerformed

    public  void onSmartPanelActionPerformed(java.awt.event.ActionEvent evt) 
    {
    }
	/*{//GEN-FIRST:event_onSmartPanelActionPerformed
        // TODO add your handling code here:
        
               MessageBox.showMessage(this, "onSmartPanelActionPerformed", "dBz");
            
        
     
    }//GEN-LAST:event_onSmartPanelActionPerformed
	*/

    
    public void setTitle(String sTitle)
    {
        titleLabel.setText(sTitle);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel componentPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton showHideButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables


 
    
    
/*
    public void addAncestorListener(ActionListener actionListener)
    {
          listenerList.add(ActionListener.class, actionListener);
    }*/

    void addActionListener(ActionListener actionListener) {
        listenerList.add(ActionListener.class, actionListener);
    }

   
   
    
   
}
